/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.wallet;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Home extends javax.swing.JFrame {
    LocalDateTime now = LocalDateTime.now();
DefaultTableModel dtm =new  DefaultTableModel();
int acum=0; 
double totalWallet=0;
double moneyAssessed=0;
String Date=now.getYear()+ "/" 
        +now.getMonthValue()+ "/" 
        +now.getDayOfMonth() + "  "
        +now.getHour()
        +":"+now.getMinute();
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    Table();
    }
   void Table(){
     String[] Title = new String [] {"ID","Type","Date","Amount"};
   dtm.setColumnIdentifiers(Title);
   tableOfExpensesIncome.setModel(dtm);
}
   void addBuy (){
       moneyAssessed=Double.parseDouble(value.getText());
    dtm.addRow(new Object []{
       acum++,"Purchase",Date,moneyAssessed
   });
}
    void addSale (){
         moneyAssessed=Double.parseDouble(value.getText());
    dtm.addRow(new Object []{
       acum++,"Sale",Date, moneyAssessed
   });   
}
    void totalBuy(){
        moneyAssessed=Double.parseDouble(value.getText());
        totalWallet=Double.parseDouble(Total.getText());
     if ( (totalWallet - moneyAssessed)>=0){
       totalWallet= totalWallet - moneyAssessed;
       Total.setText(""+totalWallet);
       addBuy();
       value.setText("");
     }else{
        JOptionPane.showMessageDialog(this,"Exceeds its current budget");
        value.setText("");
     }
    }
    void totalSale(){
          moneyAssessed=Double.parseDouble(value.getText());
          totalWallet=Double.parseDouble(Total.getText());
          totalWallet= totalWallet + moneyAssessed;
          Total.setText(""+totalWallet);
          addSale();
          value.setText("");
    }
       
    void validateImputTextBuy(){
         moneyAssessed=Double.parseDouble(value.getText());
        if (moneyAssessed>0){
            totalBuy();
        }else {
            JOptionPane.showMessageDialog(this,"Error negative numbers or amount is 0");
        value.setText("");
        }  
    }
     void validateImputTextSale(){
         moneyAssessed=Double.parseDouble(value.getText());
        if (moneyAssessed>0){
            totalSale();
        }else {
            JOptionPane.showMessageDialog(this,"Error negative numbers or amount is 0");
        value.setText("");
        }  
    }
     
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOfExpensesIncome = new javax.swing.JTable();
        value = new javax.swing.JTextField();
        Buy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        sale = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableOfExpensesIncome.setBackground(new java.awt.Color(153, 255, 102));
        tableOfExpensesIncome.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableOfExpensesIncome);

        jPanel10.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 460, 275));
        jPanel10.add(value, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 59, 78, -1));

        Buy.setBackground(new java.awt.Color(0, 0, 0));
        Buy.setForeground(new java.awt.Color(255, 255, 255));
        Buy.setText("Purchase");
        Buy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyActionPerformed(evt);
            }
        });
        jPanel10.add(Buy, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 114, -1, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TOTAL $");
        jLabel1.setOpaque(true);
        jPanel10.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 62, -1, -1));

        Total.setText(" 100.00");
        jPanel10.add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(367, 62, -1, -1));

        sale.setBackground(new java.awt.Color(0, 0, 0));
        sale.setForeground(new java.awt.Color(255, 255, 255));
        sale.setText("Sale");
        sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saleActionPerformed(evt);
            }
        });
        jPanel10.add(sale, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 114, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setOpaque(true);
        jPanel10.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyActionPerformed
     validateImputTextBuy();
    }//GEN-LAST:event_BuyActionPerformed

    private void saleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saleActionPerformed
   validateImputTextSale();
    }//GEN-LAST:event_saleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buy;
    private javax.swing.JLabel Total;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton sale;
    public volatile javax.swing.JTable tableOfExpensesIncome;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables
}
